###########################################
###         H Y P R L A N D   M A I N   ###
###########################################

# Include modular configs
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/misc.conf

# Update environment for session
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

###########################################
###        SwayOSD Layer Rules          ###
###########################################
layerrule = blur, class:^(swayosd)$




layerrule = blur, class:^(waybar|swayosd)$
