#################
### AUTOSTART ###
#################

exec-once = nm-applet
exec-once = hyprpaper
exec-once = waybar
exec-once = swaync
exec-once = swayosd-server 

# Start clipboard history
exec-once = wl-paste --watch cliphist store



# ─── Eww Reactor Monitor ───
exec-once = eww daemon
exec-once = eww open visualizer_window
exec-once = eww open cpu_ram_storage_bars
exec-once = eww open power_mode_text
exec-once = eww open right_fan_data
exec-once = eww open right_internet_text

