##############################
### WINDOWS AND WORKSPACES ###
##############################

# Prevent accidental maximize animations
windowrule = suppressevent maximize, class:.*

# Fix for Xwayland floating windows (like some dialogs)
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# ==== Kitty Blur + Opacity ====
windowrulev2 = opacity 0.9 0.85, class:^(kitty)$

# Optional: prevent blur on special windows like wlogout or swayosd overlays
windowrulev2 = nofocus, class:^(wlogout)$
windowrulev2 = nofocus, class:^(swayosd)$

# ==== Floating/Centering/Blur for wlogout ====
windowrulev2 = float, class:^(wlogout)$
windowrulev2 = center, class:^(wlogout)$
windowrulev2 = stayfocused, class:^(wlogout)$
layerrule = blur, wlogout